In [1]:
#Importação
import pandas as pd

In [2]:
#Listas Importantes:
Fev31_15min = []
FevNorm_15min = []
anos = ['1997','1998','1999','2000','2001','2002','2003','2004','2005',
        '2006','2007','2008','2009','2010','2011','2012','2013','2014',
        '2015','2016','2017','2018','2019','2020','2021','2022']

Esse Código extrai os valores Pluviométricos de Fevereiro de 31 dias e os valores normalizados de Fevereiro Normal e de 31 dias, por estação, em forma de DataFrame csv.

In [3]:
#Código:
pasta = input('Digite a Estação: ')
diretorio = r'D:\Estudo\Oficina de Pesquisa\Dados Tradados'

#Tratando as entradas:
tamanho = pasta.split()
if len(tamanho) != 1:
    elemento = ('_'.join(tamanho)).lower()
else:
    elemento = pasta.lower()

#Fevereiro de 31 Dias:
for ano in anos:
    arquivo = pd.read_csv(diretorio+'\\'+pasta+'\\'+elemento+'_fev31_'+ano+'.csv', sep=',')
    arquivo[arquivo['15 min'] == 'ND'] = 0 
    arquivo[['15 min']] = arquivo[['15 min']].apply(pd.to_numeric)
    soma = arquivo['15 min'].sum()
    Fev31_15min.append(soma)

#Fevereiro Normal:
for ano in anos:
    arquivo = pd.read_csv(diretorio+'\\'+pasta+'\\'+elemento+'_Normal_'+ano+'.csv', sep=',')
    arquivo[arquivo['15 min'] == 'ND'] = 0 
    arquivo[['15 min']] = arquivo[['15 min']].apply(pd.to_numeric)
    soma = arquivo['15 min'].sum()
    FevNorm_15min.append(soma)

lista_de_tuplas = list(zip(anos,Fev31_15min,FevNorm_15min))

df = pd.DataFrame(lista_de_tuplas, columns=['Anos','Fev31','FevNormal'])
df['Fev31N'] = df['Fev31'] /31
df.to_csv(diretorio+'\\'+elemento+'_Final.csv', index = False)

df

Digite a Estação: campo grande

    Anos  Fev31  FevNormal     Fev31N
0   1997   81.0       57.2   2.612903
1   1998  213.3      213.3   6.880645
2   1999   64.2       64.0   2.070968
3   2000  139.3      139.3   4.493548
4   2001   72.2       72.2   2.329032
5   2002  116.8      116.8   3.767742
6   2003   27.6        8.8   0.890323
7   2004   86.2       86.2   2.780645
8   2005  151.0       89.0   4.870968
9   2006   93.2       93.2   3.006452
10  2007  162.6      162.6   5.245161
11  2008  175.2      164.6   5.651613
12  2009   76.6       76.6   2.470968
13  2010  135.2       73.8   4.361290
14  2011   30.4       23.2   0.980645
15  2012   74.0       74.0   2.387097
16  2013  130.0      125.4   4.193548
17  2014   64.4       64.2   2.077419
18  2015  119.8      119.8   3.864516
19  2016  137.6      128.0   4.438710
20  2017   19.4       15.6   0.625806
21  2018  119.2      117.8   3.845161
22  2019  284.6      220.4   9.180645
23  2020  339.6      272.0  10.954839
24  2021  137.4      137.4   4.432258
25  2022  166.6      166.6   5.374194